image: node:8.9
pipelines:
  default:
    - step:
        script:
          - npm install
          - npm run test
          - npm run test-server
          - npm run build-node-sdk
          - npm run build-browser-sdk
          - npm run build-server-sdk